app.get('/generate', async (req, res) => {
  const deepai = require('deepai');
  deepai.setApiKey(process.env.APIKEY);

   const songList = [
      "Stronger",
      "Baby Love",
      "Poncho & Lefty",
      "Truth Hurts",
      "Without You",
      "You're so Vain",
      "Time After Time",
      "Where Is My Mind?",
      "So What",
      "Welcome To The Jungle",
      "Old Town Road",
      "Cannonball",
      "House Of Balloons / Glass Table Girls",
      "Cranes in the Sky",
      "A Milli",
      "212",
      "Buddy Holly",
      "I Can't Help Myself",
      "Bad Romance",
      "Cross Road Blues",
      "Just a Friend",
      "Oye Como Va",
      "Back That Azz Up",
      "Our Lips Are Sealed",
      "Sunday Mornin' Comin' Down",
      "Rhythm Nation",
      "Move on Up",
      "Stand By Your Man",
      "Solsbury Hill",
      "House of the Rising Sun",
      "Midnight Train to Georgia",
      "Goodbye Earl",
      "Fade Into You",
      "Come As You Are",
      "Never Too Much",
      "Get Lucky",
      "Help Me",
      "Boom Boom",
      "Into the Mystic",
      "Crying",
      "Ku Klux Klan",
      "No Ordinary Love",
      "Loser",
      "Livin' On A Prayer",
      "Summertime Sadness",
      "White Rabbit",
      "Bam Bam",
      "The Rain",
      "Africa",
      "Bad and Boujee",
      "Powderfinger",
      "The Reaper",
      "Tyrone",
      "Help!",
      "Rosalita",
      "Cosmic Dancer",
      "In Da Club",
      "Sugar, We're Goin Down",
      "Ace of Spades",
      "The House That Built Me",
      "If I Ain't Got You",
      "La Vida Es Un Carnaval",
      "Savage Remix",
      "Passionate Kisses",
      "Call Me Maybe",
      "Limelight",
      "Sheena Is a Punk Rocker",
      "West End Girls",
      "Summertime Blues",
      "Adore",
      "They Reminisce Over You",
      "Under Pressure",
      "Sign of the Times",
      "Rapper's Delight",
      "Super Bass",
      "Mannish Boy",
      "No Diggity",
      "Criminal",
      "Flava in Ya Ear",
      "How Soon Is Now?",
      "California Dreamin'",
      "Fantasy",
      "Green Onions",
      "Uptown Funk",
      "Alive",
      "Enjoy the Silence",
      "Dreaming",
      "Gloria",
      "Buffalo Stance",
      "Heavy Metal Drummer",
      "Whipping Post",
      "Everlong",
      "Father And Son",
      "Free Bird",
      "Sucker M.C.'s",
      "Amor Prohibido",
      "Rock And Roll All Nite",
      "Ain't Nobody",
      "Lovely Day",
      "Go Your Own Way",
      "Station to Station",
      "You Make Me Feel",
      "Hungry Like the Wolf",
      "Bring The Noise",
      "Alison",
      "Planet Rock",
      "Grace",
      "Say It Loud - I'm Black And I'm Proud",
      "Fix You",
      "Springsteen",
      "Enter Sandman",
      "Brass in Pocket",
      "Party Up",
      "Personality Crisis",
      "Lola",
      "I'm Coming Out",
      "I Like It",
      "Redbone",
      "Paper Bag",
      "Typical Girls",
      "Radiation Vibe",
      "Untitled",
      "Mr. Brightside",
      "Pictures Of You",
      "Mama Tried",
      "Up on the Roof",
      "Be Thankful for What You Got",
      "Hotline Bling",
      "I Can't Make You Love Me",
      "Bennie And The Jets",
      "Peggy Sue",
      "Just What I Needed",
      "Black Hole Sun",
      "Thinkin Bout You",
      "Da Doo Ron Ron",
      "God Save The Queen",
      "Box of Rain",
      "Could You Be Loved",
      "Merry Go 'Round",
      "The Harder They Come",
      "Little Red Corvette",
      "Killing Me Softly With His Song",
      "Because the Night",
      "Blank Space",
      "Surrender",
      "Don't Leave Me This Way",
      "Rock with You",
      "Sweet Dreams",
      "It Was A Good Day",
      "Ponta De Lanca Africano",
      "Angel from Montgomery",
      "Time of the Season",
      "Virginia Plain",
      "Heartbreak Hotel",
      "Dynamite",
      "It's Too Late",
      "Iron Man",
      "What a Fool Believes",
      "Promised Land",
      "I'm a Believer",
      "in Hammersmith Palais",
      "1999",
      "Paranoid",
      "Believe",
      "She's Gone",
      "Move Your Body",
      "Ripple",
      "Papa Was A Rollin' Stone",
      "Umbrella",
      "Please Mr. Postman",
      "Big Poppa",
      "Safaera",
      "Under the Bridge",
      "Real Love",
      "Portions for Foxes",
      "Lust For Life",
      "Scenes from an Italian Restaurant",
      "All I Have to Do Is Dream",
      "After the Gold Rush",
      "I Still Haven't Found What I'm Looking For",
      "California Love",
      "Everybody Wants To Rule The World",
      "Hound Dog",
      "Visions of Johanna",
      "Leader Of The Pack",
      "A Love Supreme",
      "I Wanna Be Your Dog",
      "The Tears Of A Clown",
      "Walk On By",
      "Hotel California",
      "Light My Fire",
      "Ain't No Sunshine",
      "Divorce Song",
      "Crazy",
      "Chain of Fools",
      "Every Breath You Take",
      "Trans-Europe Express",
      "No Scrubs",
      "Wish You Were Here",
      "Night Moves",
      "Rock Lobster",
      "I Put a Spell On You",
      "Jungleland",
      "Wouldn't It Be Nice",
      "Rebel Girl",
      "Won't Get Fooled Again",
      "Sweet Jane",
      "School's Out",
      "Can I Kick It?",
      "In The Air Tonight",
      "Yeah!",
      "Atlantic City",
      "That's the Joint",
      "You Shook Me All Night Long",
      "Dancing Queen",
      "Say My Name",
      "Suzanne",
      "Georgia on My Mind",
      "Never Tear Us Apart",
      "Grindin'",
      "Penny Lane",
      "Karma Police",
      "Pressure Drop",
      "Bo Diddley",
      "Ever Fallen in Love Version",
      "Sail Away",
      "Love and Happiness",
      "Killing Me Softly With His Song",
      "The Boys Are Back In Town",
      "A Whiter Shade of Pale",
      "Closer",
      "Unchained Melody",
      "Shout",
      "Take Care",
      "King Tubby Meets Rockers Uptown",
      "Left of the Dial",
      "Let's Get It On",
      "Coat of Many Colors",
      "American Tune",
      "Pusherman",
      "Get Up, Stand Up",
      "Heart of Gold",
      "The Revolution Will Not Be Televised",
      "Heat Wave",
      "Master Of Puppets",
      "Coal Miner's Daughter",
      "Stop! In The Name Of Love",
      "Blue Eyes Crying In the Rain",
      "Flash Light",
      "I Will Survive",
      "Purple Haze",
      "Bad Reputation",
      "Straight Outta Compton",
      "River",
      "Ooh La La",
      "Sabotage",
      "Summer Babe",
      "Eleanor Rigby",
      "Great Balls of Fire",
      "The Humpty Dance",
      "I Want It That Way",
      "September Gurls",
      "Are You That Somebody",
      "Your Cheatin' Heart",
      "Lean on Me",
      "Blue Monday",
      "You Keep Me Hangin' On",
      "Groove Is in the Heart",
      "My Generation",
      "I Wanna Dance with Somebody",
      "Mr. Tambourine Man",
      "This Land is Your Land",
      "Single Ladies",
      "Fortunate Son",
      "There Is a Light That Never Goes Out",
      "Both Sides Now",
      "Layla",
      "Stan",
      "Judy Blue Eyes",
      "River Deep - Mountain High",
      "Bizarre Love Triangle",
      "Free Fallin'",
      "In the Midnight Hour",
      "Edge of Seventeen",
      "Jailhouse Rock",
      "Shook Ones",
      "Deacon Blues",
      "Paint It Black",
      "More Than a Feeling",
      "With Or Without You",
      "One Nation Under a Groove",
      "The Boys Of Summer",
      "Doll Parts",
      "Killing In The Name",
      "Wichita Lineman",
      "...Baby One More Time",
      "Young Americans",
      "Signed, Sealed, Delivered",
      "Your Song",
      "Ring of Fire",
      "Changes",
      "Dream On",
      "Sexual Healing",
      "I Can't Stand the Rain",
      "Get Up I Feel Like Being A Sex Machine",
      "Crazy",
      "Rid Of Me",
      "Wild Horses",
      "Mind Playing Tricks on Me",
      "Ode To Billie Joe",
      "Fuck Tha Police",
      "Space Oddity",
      "Little Wing",
      "Subterranean Homesick Blues",
      "I'll Take You There",
      "Beat It",
      "Nothing Compares 2 U",
      "You Are The Sunshine Of My Life",
      "The Sounds of Silence",
      "Eight Miles High",
      "Walk On the Wild Side",
      "Comfortably Numb",
      "bad guy",
      "Jump",
      "You Really Got Me",
      "I Only Have Eyes for You",
      "Radio Free Europe",
      "Marquee Moon",
      "Mississippi Goddam",
      "What A Wonderful World",
      "In The Still of the Night",
      "American Girl",
      "Son Of A Preacher Man",
      "Lose Yourself",
      "All the Young Dudes",
      "I'm So Lonesome I Could Cry",
      "Mr. Tambourine Man",
      "Landslide",
      "Pink Moon",
      "Into the Groove",
      "Nightswimming",
      "Baba O'Riley",
      "Cissy Strut",
      "Teen Age Riot",
      "Louie Louie",
      "Last Nite",
      "Spoonful",
      "Super Freak",
      "Proud Mary",
      "Will You Still Love Me Tomorrow",
      "Basket Case",
      "Rocket Man",
      "Kashmir",
      "Blueberry Hill",
      "Fire and Rain",
      "Ms. Jackson",
      "Jumpin' Jack Flash",
      "London Calling",
      "He Stopped Loving Her Today",
      "Maggie May",
      "No Woman No Cry",
      "Vogue",
      "Heart Of Glass",
      "thank u, next",
      "Try a Little Tenderness",
      "She Loves You",
      "What's Love Got to Do with It",
      "Don't Stop Believin'",
      "Paid In Full",
      "Stand by Me",
      "Dancing In The Street",
      "Hold On, We're Going Home",
  "Whole Lotta Love",
      "Waterfalls",
      "Freedom!",
      "Anarchy In The UK",
      "That'll Be the Day",
      "This Must Be the Place",
      "People Get Ready",
      "Let It Be",
      "Oh Bondage! Up Yours!",
      "I Heard It Through The Grapevine",
      "Creep",
      "I Say a Little Prayer",
      "It Takes Two",
      "At Last",
      "Toxic",
      "Higher Ground",
      "Losing My Religion",
      "Thunder Road",
      "Something",
      "Everyday People",
      "Just Like Heaven",
      "C.R.E.A.M.",
      "Sympathy For The Devil",
      "Life on Mars?",
      "I Want You Back",
      "You Oughta Know",
      "Maybelline",
      "Maps",
      "Blowin' in the Wind",
      "Stayin Alive",
      "In My Life",
      "Gloria",
      "99 Problems",
      "Wonderwall",
      "I Will Always Love You",
      "Since U Been Gone",
      "Good Golly Miss Molly",
      "Int'l Players Anthem",
      "A Natural Woman",
      "Hey Jude",
      "Sweet Child O' Mine",
      "All My Friends",
      "Tumbling Dice",
      "Kiss",
      "Let's Stay Together",
      "Desolation Row",
      "Rolling in the Deep",
      "I'm Waiting For The Man",
      "What'd I Say",
      "Back To Black",
      "Reach Out I'll Be There",
      "Roadrunner",
      "I Walk the Line",
      "Common People",
      "Hallelujah",
      "Formation",
      "Yesterday",
      "Fast Car",
      "Suspicious Minds",
      "All Too Well",
      "Good Times",
      "Tangled up in Blue",
      "Bridge Over Troubled Water",
      "September",
      "Blitzkrieg Bop",
      "Jolene",
      "One",
      "Stairway to Heaven",
      "Running Up That Hill",
      "The Message",
      "The Weight",
      "Family Affair",
      "Work It",
      "Like a Prayer",
      "The Tracks Of My Tears",
      "Good Vibrations",
      "I Feel Love",
      "Walk on By",
      "Gasolina",
      "Doo Wop",
      "Idioteque",
      "Tiny Dancer",
      "Paper Planes",
      "Alright",
      "Billie Jean",
      "My Girl",
      "Redemption Song",
      "Love Will Tear Us Apart",
      "All Along the Watchtower",
      "Bombs Over Baghdad",
      "the Dock of the Bay",
      "When Doves Cry",
      "Seven Nation Army",
      "Tutti Frutti",
      "Papa's Got A Brand New Bag",
      "Johnny B. Goode",
      "Juicy",
      "Satisfaction",
      "Royals",
      "Nuthin' But A G Thang",
      "Once in a Lifetime",
      "Born to Run",
      "A Case of You",
      "Runaway",
      "A Day In The Life",
      "Heroes",
      "Be My Baby",
      "Strange Fruit",
      "Dancing On My Own",
      "Imagine",
      "Purple Rain",
      "Bohemian Rhapsody",
      "Crazy In Love",
      "I Want To Hold Your Hand",
      "Waterloo Sunset",
      "Gimme Shelter",
      "Superstition",
      "God Only Knows",
      "Hey Ya!",
      "Dreams",
      "Get Ur Freak On",
      "Strawberry Fields Forever",
      "What's Going On",
      "Smells Like Teen Spirit",
      "Like a Rolling Stone",
      "A Change Is Gonna Come",
      "Fight The Power",
      "Respect"
    ];

  const results = [];

  for (let title of songList) {
    try {
      // Generate image
      const resp = await deepai.callStandardApi("text2img", { text: title });

      // Fetch image as base64
      const imageResp = await axios.get(resp.output_url, { responseType: "arraybuffer" });
      const returnedB64 = Buffer.from(imageResp.data).toString("base64");
      const fullB64String = `data:${imageResp.headers["content-type"]};base64,${returnedB64}`;

      // Insert into database
      try {
        const query = "INSERT INTO songs(title, image) VALUES ($1, $2) WHERE NOT EXISTS (SELECT 1 FROM songs WHERE title = $1)";
        const params = [title, fullB64String];
        await pool.query(query, params);

        console.log(`Inserted song into database: ${title}`);
        results.push({ title, success: true });
      } catch (dbErr) {
        console.log(`Failed to insert [${title}] into db: ${dbErr.message}`);
        results.push({ title, success: false, error: dbErr.message });
      }
    } catch (imgErr) {
      console.log(`Failed to generate image for [${title}]: ${imgErr.message}`);
      results.push({ title, success: false, error: imgErr.message });
    }
  }

  res.json({ message: "Done processing songs", results });
});